#!/bin/bash

# Setup script for local development with production Clerk keys

echo "========================================"
echo "AWE Local Development Setup with Clerk"
echo "========================================"
echo ""
echo "The production Clerk keys are restricted to the domain 'awe.dukelic.com'."
echo "To test locally with production Clerk, you have these options:"
echo ""
echo "OPTION 1: Use a local subdomain (Recommended)"
echo "----------------------------------------"
echo "1. Add this line to your /etc/hosts file:"
echo "   127.0.0.1 local.awe.dukelic.com"
echo ""
echo "2. Access the app at: http://local.awe.dukelic.com:3000"
echo ""
echo "To add the hosts entry, run:"
echo "  sudo sh -c 'echo \"127.0.0.1 local.awe.dukelic.com\" >> /etc/hosts'"
echo ""
echo "OPTION 2: Request Clerk Development Keys"
echo "----------------------------------------"
echo "1. Go to https://dashboard.clerk.com"
echo "2. Create a development instance"
echo "3. Update .env.local with development keys"
echo ""
echo "OPTION 3: Add localhost to Clerk Dashboard"
echo "----------------------------------------"
echo "1. Go to https://dashboard.clerk.com"
echo "2. Navigate to your production instance"
echo "3. Go to 'Domains' or 'Allowed Origins'"
echo "4. Add 'localhost:3000' (if allowed)"
echo ""
echo "Current Status:"
echo "---------------"
if grep -q "local.awe.dukelic.com" /etc/hosts 2>/dev/null; then
    echo "✅ local.awe.dukelic.com is configured in /etc/hosts"
    echo "   You can access the app at: http://local.awe.dukelic.com:3000"
else
    echo "❌ local.awe.dukelic.com is NOT configured in /etc/hosts"
    echo "   Run the command above to configure it"
fi
echo ""